### ISSUE TITLE
Travis CI C++11

### ISSUE THREAD

**Issue by konopka90** [wheybags/freeablo#132]
Have you considered using C++11 in project ? I know there is old version of g++ on Travis but I think it is possible to upgrade to ver 4.8.x or 4.9.x. C++11 makes life easier. There shouldn't be any problem with compilation of existing sources and dependencies.

**Comment by bradc6** [comment]
I agree with konopka90 about C++11, but may I suggest going a little farther to C++14? (I am using TravisCI with C++14 for my libgrp project if you would like an example https://github.com/Stratagus/libgrp/tree/develop)

**Comment by konopka90** [comment]
Good idea, specially that we have the example.

**Comment by wheybags** [comment]
Yeah, I have considered it, and tbh I haven't really come to a conclusion.
A big blocker is that we still use vs2010 for windows, so we'd need to upgrade that which would be a major hassle.
I definitely wouldn't go to c++14, but c++11 is prooobably a good idea.
(aka, fix the windows build system + travis and I will :p)

**Comment by konopka90** [comment]
I will try to compile w32 libraries with vs2013

**Comment by wheybags** [comment]
Make a pr for http://github.com/wheybags/freeablo-windows-build if you get it working

**Comment by konopka90** [comment]
It's really hard to get it working - librocket demands python27.lib even if I compile debug version. When I add python27.lib to linker it says: "Error	305	error LNK2001: unresolved external symbol "__declspec(dllimport) void * __cdecl boost::python::objects::find_static_type(void *,struct boost::python::type_info,struct boost::python::type_info)" 
etc. 

Wrrrrrr, so many hours lost -.-

**Comment by wheybags** [comment]
I think you have to define some preporcessor symbol to tell boost it's
being linked statically.
BOOST_PYTHON_STATIC iirc

**Comment by konopka90** [comment]
BOOST_PYTHON_STATIC_LIB, wow it's working.

**Comment by konopka90** [comment]
Finally I compiled libs but:
1) as previously there is a problem with Py_Initialize() in debug mode - it calls abort()
2) in release mode game is running but I got RuntimeError:
"Traceback (most recent call last):
  File ".\rocket.py", line 4, in <module>
    from _rocketcontrols import *
RuntimeError: extension class wrapper for base class class Rocket::Core::Element
 has not been created yet"

Any idea what to do ?

**Comment by konopka90** [comment]
P.s. Boost and librocket is compiled statically with BOOST_PYTHON_STATIC_LIB

**Comment by konopka90** [comment]
Second problem solved. 
Regarding to first problem I don't know what I'm doing wrong - before abort() I got message:
"Assertion failed: (op->_ob_prev == NULL) == (op->_ob_next == NULL), file ..\Obje
cts\object.c, line 65" in Python source code. 
I compiled Boost.Python using bjam with flag "<python-debugging>on" , it should work properly.. I can't find any solution in the Internet.

**Comment by wheybags** [comment]
Sorry for slow response on this but... The Witcher 3 was released :3

**Comment by konopka90** [comment]
Great game. Maybe I will try to send my resume to CD Project :>

Still I got problem with debugging on windows in Debug mode but... debugging in RelWithDebug mode in VS works perfectly!

**Comment by wheybags** [comment]
Pulled that in, so we can start using c++11 now.
Still need to update the cmake files to enable it + port whatever boost stuff we don't need anymore

**Comment by rubdos** [comment]
Not that I'm affiliated with this project; just stumbled on it today, but I still wanted to give my €0.02 on C++11/14; why does a GPL project like this depend on a proprietary compiler? I always found that mingw-w64 worked pretty well for Windows.

Using mingw-w64 would mean being less dependent on Microsoft fixing a compiler for free software projects and, afaik, mingw-w64 includes c++14 support out of the box.

Just my two cents though.

**Comment by mloccy** [comment]
It's not depending on it though, anyone can build it with any compiler
toolchain on windows as they please, the main dev just chose VS because
it's convenient for him.

**Comment by wheybags** [comment]
The idea is to make contributing less intimidating for windows devs, as
getting a build environment up from scratch is a massive pain. And existing
windows devs are almost certainly using vs.

**Comment by rubdos** [comment]
Ok, I see. This is just an idea that comes to my mind every time I see
people building GPL'ed stuff on VC++. Doesn't feel good to me.

**Comment by konopka90** [comment]
Remove boost stuff : #156 and #151

**Comment by mloccy** [comment]
this should be closed, you can't build the project without C++11 now !!
