### ISSUE TITLE
Eat your vegatables and brush after every meal

### ISSUE THREAD

**Issue by konopka90** [wheybags/freeablo#135]
Eat your vegatables and brush after every meal

https://www.youtube.com/watch?v=CpWKan8L76Q

**Comment by wheybags** [comment]
critical v0.3 feature

**Comment by wheybags** [comment]
(actually, this may not be the right place, but in case it seems like I've been doing nothing for the past ages, I've actually been working on dungeon level 3 generation, got it nearly working, had to overhaul a whole bunch of stuff to do with the level generator)

**Comment by mewmew** [comment]
> (actually, this may not be the right place, but in case it seems like I've been doing nothing for the past ages, I've actually been working on dungeon level 3 generation, got it nearly working, had to overhaul a whole bunch of stuff to do with the level generator)

Thanks for the status update :) Perhaps *the right place*™ for these status updates may be http://freeablo.org and http://khanduras.net?
