### ISSUE TITLE
The package for Arch Linux

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#139]
HI

Wolfyrion on this forum pointed out that you can download package for Arch Linux

https://www.gamingonlinux.com/forum/topic/1670?page=1
https://aur.archlinux.org/packages/freeablo/

Can you add this information into the file readme.md?

**Comment by wheybags** [comment]
That package is just run by some guy, it's not official.
Eventually we'll try get proper packages going for all the major distros, then we'll advertise those on the website
