### ISSUE TITLE
refactor rendering

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#149]

**Comment by mloccy** [comment]
Might as well fix the renderer so that it only renders what's in the viewport if you're going to refactor it.

**Comment by konopka90** [comment]
Big issue is about rendering bitmap fonts in GUI - as we know development of librocket stopped long time ago. This PR https://github.com/libRocket/libRocket/pull/34 is impossible to merge. It needs to be reimplemented from scratch what will introduce a lot of changes in librocket. I have no idea how to solve this problem - try to improve librocket, maybe librocket + CEGUI or totally remove librocket from the project or something else.

**Comment by ChefKeeper** [comment]
Hello,
I'm looking forward to contribute !
What exactly needs to be done or redone with rendering ?
(I'm not saying I'll do it, I just need to understand before deciding)

**Comment by wheybags** [comment]
Hi!
Sorry for the delay, meant to reply sooner.
It's great to hear that you want to contribute. However, refactoring rendering is probably not the best place to start (it's components/render/sdl2backend.cpp that's the problem, the nastiest magic-number fueled code in the project :p).
If you're looking for something ambitious to do though, why not try to integrate pathfinding to make the monsters actually go towards the player?
@konopka90  actually wrote an implementation of the A* pathfinding algorithm, but it hasn't been integrated with the freeablo character/level system and is sitting in a PR (#155).

To give some pointers on how to get started: all entities (players, npcs and monsters) in the world are instances of FAWorld::Actor. The actor class has an update function that is called every frame. In this update function, there is code that will move the npc towards a location held in the mDestination member. The position is held in the mPosition member which is an instance of the FAWorld::Position class. Position defines a location on the game grid, accounting for the fact that an actor can be in between two adjacent tiles. To do this it essentially stores two grid locations, the current and next tile coord (but the next coord is just stored as a direction, since it is always adjacent to the current), and then also where the actor is between them as an int between 0 and 100.

The current code will just move in a line toward the actor's mDestination, but it would be nice if we could have it pathfind towards it instead. It would also be nice if hostile NPCs (FAWorld::Monster) would set their mDestination to players locations when inside a certain radius of them.

So that ended up being a bit of an essay, but anyway, hope you're interested in that job but if not it's a nice description for someone to pick up anyway :p

**Comment by ChefKeeper** [comment]
Hey no problem we all got jobs ;)
All right I'll look to integrate his PR sounds fun :) 
And I saw somewhere you said you also need someone reversing the d1 exe ? Can't find where you said it but what do you need ? just other versions of diablo, so they all work ? or was something missing for 1.09 ?

Thanks for all this informations, I'll read the code a bit before starting, and I'll tell you if I can't do it ^^

By the way where is the best place to discuss development, forum or github ?

**Comment by wheybags** [comment]
There will be some more stuff we'll need from the exe at some point
probably, not sure what yet.
It would be nice to get offsets for data in other versions of the exe, the
files here:
https://github.com/wheybags/freeablo/tree/master/resources/exeversions
define the locations atm (1.09b is almost exactly the same as 1.09 so it's
just a symlink).
As for development discussion, whatever you feel like, really.
I get email notifications for both so I'll see it regardless :p

**Comment by mewmew** [comment]
> And I saw somewhere you said you also need someone reversing the d1 exe ?

Hej @ChefKeeper! If you are into reversing d1, you'd be more than welcome to join our endavour of organizing this information and distributing it in a public forum.

To get started, have a look at 

https://freeablo.org/forum/viewtopic.php?f=4&t=9

and

https://github.com/sanctuary/notes

with a public chat at 

https://gitter.im/sanctuary/notes

Cheers /u

**Comment by ChefKeeper** [comment]
Hi @mewmew I'm a total beginer in RE but I'm learning right now and it's very interesting, however thanks for theses links !

**Comment by Fuco1** [comment]
There is a project called "The Hell mod" which is going on for good 10 years now, they've done gazilion patches to the original diablo+hellfire, almost all assembly hacks.

Sometimes during 2009 there was work going on on "The Hell 2" which was a decompiled diablo1 being rewritten into C++ and cleaned up (I did some work on UI rendering back then).  In the last 2-3 months they revived that project.

Even back then we had thousands of note files on just about anything.  I suppose it would be a good idea to try to get in touch with the team.

**Comment by mewmew** [comment]
> Even back then we had thousands of note files on just about anything. I suppose it would be a good idea to try to get in touch with the team.

Hi @Fuco1!

I know, The Hell Mod has done some intense analysis of the assembly. If you've been in touch with the developers before, would you mind asking if it would be possible on collaborating on organizing these notes somewhere?

Cheers /u

**Comment by cjwijtmans** [comment]
I wonder if QT can be purposed to render gaming UIs.

**Comment by wheybags** [comment]
(Late, but whatever :p) It could, but it doesn't play very nice with 3d
renderers. It would want to control the main loop, and typically you'd want
to do that yourself in a game. Iirc it has some opengl integration, but it
would be more opengl in qt than qt in opengl

**Comment by cjwijtmans** [comment]
Yeah you are right. What about GTK+? I have been looking for something to use myself but nothing seems to cut it.

**Comment by wheybags** [comment]
I used gtk in a work project a few years ago and it was _awful_. I'd also
say it would have the same problems as qt. Yeah, nothing does cut it. It's
amazing that in 2016 there are still no real good options for video game
GUI libraries.

**Comment by ChefKeeper** [comment]
What about http://mygui.info/ ?

**Comment by wheybags** [comment]
It's a possibility, yeah. The requirements I have are:
- Isn't tied to any rendering api, allows the user to overwrite it's
rendering backend so it can be integrated into anything.
- Easily scriptable (preferably with a built in scripting language, but
just being easy to lump one in on top is OK too)
- Can be passed resources from memory buffers, we need to have it use CEL
and CL2 files
- GUI elements can be overwritten at runtime by just editing layout files
and scripts, allowing users to make GUI mods.
- Not a dead project.

Librocket meets all of these except that last one. It also uses Python for
scripting (can use lua too though now), and I'm not a huge fan of python
for this purpose.
Ideally the scripting language used would be lua.
I had a look at the mygui docs and tbh I can't tell if it meets any of
those or not.
If anyone knows of a good library that does, please do let me know.

**Comment by wheybags** [comment]
Actually, @scrawl, you' know, how does mygui fare on these points? (To summarise, looking for a decent GUI library, list of requirements is in the post above this)

**Comment by scrawl** [comment]
I think MyGUI has all of those requirements except for the built in scripting language. However since you're coming from libRocket, it should be noted that MyGUI's layout/skinning system is not quite as powerful as HTML/CSS and can be a little unintuitive sometimes.

**Comment by wheybags** [comment]
renderer has been moved to opengl. Still needs more refactoring later, but gonna close this issue for now
