### ISSUE TITLE
refactor load/save settings from file

### ISSUE THREAD

**Issue by konopka90** [wheybags/freeablo#150]
Summing up:
- celview uses QSettings
- freeablo uses own implementation in "loadSettings" function
- freeablo uses component "Misc::readIni" in runGameLoop function
- diabloexe uses component "Misc::readIni"
- FALevelGen uses component "Misc::readIni"
- launcher uses component "Settings"

I suggest to modify component "Settings" and use it in every subproject.

**Comment by wheybags** [comment]
Yeah, I agree.
We should probably use the boost json lib in our own settings component.
Would you be interested in taking this task?

**Comment by konopka90** [comment]
Yes, I'm working on it. 
I know that Ini files are deprecated but I think it is more readable than json.

**Comment by wheybags** [comment]
I'm not too pushed, INI will definitely do for now

**Comment by konopka90** [comment]
#151
