### ISSUE TITLE
[libRocket] Bitmap fonts

### ISSUE THREAD

**Issue by konopka90** [wheybags/freeablo#167]
Finally I've got working!!! bitmap fonts with latest librocket master. 

LibRocket fork with changes: https://github.com/konopka90/libRocket
Example usage in freeablo: https://github.com/konopka90/freeablo/tree/bitmap_font

There are a lot of problems ofc but I think it is easy to fix.

**Comment by wheybags** [comment]
nice! :cookie:  omnom

**Comment by konopka90** [comment]
aghr, some changes still on local branch

**Comment by wheybags** [comment]
just tried it there, looks like it's working pretty well.
So, you added a bitmap font interface that we can implement with a freeablo font implementation?
You should make a pull request upstream to libRocket too.

**Comment by konopka90** [comment]
Yes but there is a lot of commented out code and other ugly things, I have to work on it, next week should be done.
