### ISSUE TITLE
Error: ‘titleScreen’ was not declared in this scope

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#193]
Hi

I want to inform you that I can't compile the new version of Freeablo:

 make
[ 72%] Built target StormLib
[ 72%] Built target Audio
[ 74%] Built target Cel
[ 75%] Built target Misc
[ 77%] Built target DiabloExe
[ 78%] Built target FAIO
[ 79%] Built target Input
[ 80%] Built target Levels
[ 82%] Built target Render
[ 83%] Built target Script
[ 83%] Built target Settings
[ 83%] Building CXX object apps/freeablo/CMakeFiles/freeablo.dir/fagui/guimanager.cpp.o
/home/user/Desktop/diablo9/freeablo/apps/freeablo/fagui/guimanager.cpp: In member function ‘void FAGui::GuiManager::showTitleScreen()’:
/home/user/Desktop/diablo9/freeablo/apps/freeablo/fagui/guimanager.cpp:56:21: error: ‘titleScreen’ was not declared in this scope
         startFadeIn(titleScreen);
                     ^
make[2]: *** [apps/freeablo/CMakeFiles/freeablo.dir/fagui/guimanager.cpp.o] Error 1
make[1]: *** [apps/freeablo/CMakeFiles/freeablo.dir/all] Error 2
make: *** [all] Error 2

uname -a

Linux user-Macmini 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 14.04

**Comment by konopka90** [comment]
Thanks!

**Comment by konopka90** [comment]
https://github.com/wheybags/freeablo/pull/194

**Comment by gbudny** [comment]
Thank you.

Now I can compile Freeablo without any issues.
