### ISSUE TITLE
 No such slot Launcher::ProcessInvoker::processError

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#196]
Hi

I want to inform you that I see this error every time when I try to run the launcher:

./launcher
QObject::connect: No such slot Launcher::ProcessInvoker::processError(QProcess::ProcessError)

 uname -a
Linux user-Macmini 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by konopka90** [comment]
Closes https://github.com/wheybags/freeablo/pull/200
