### ISSUE TITLE
mpqtool: 'std::logic_error'

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#197]
Hi

I noticed this binary file in the Freeablo directory, but I can not run it:

./mpqtool
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

uname -a
Linux use-Macmini 3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by konopka90** [comment]
Hi, it expects one argument - path to file. Try ./mpqtool PATH_TO_DIABDAT.MPQ

**Comment by wheybags** [comment]
Nope, actually it expects two args, the first is a path inside the
mpq(source), the second is a local path (destination).
It will extract the source to the destination. It depends on having
DIABDAT.MPQ in the working dir

**Comment by gbudny** [comment]
I am not sure if this command is correct:

ls
apps         CMakeCache.txt       components   exedump   launcher  resources
celview      CMakeFiles           DIABDAT.MPQ  extern    Makefile
celview.ini  cmake_install.cmake  Diablo.exe   freeablo  mpqtool

 ./mpqtool DIABDAT.MPQ .
Segmentation fault (core dumped)

**Comment by wheybags** [comment]
no, it doesn't take the mpq as an argument, jsut two file paths as I said
in the last post.
eg: ./mpqtool "levels/l2data/l2.min" l2.min
and then you'll have l2.min extracted from the mpq in your current dir

**Comment by gbudny** [comment]
Thank you.

It works now.

./mpqtool "levels/l2data/l2.min" l2.min
levels\l2data\l2.min

 ls
apps         CMakeCache.txt       components   exedump   l2.min    mpqtool
celview      CMakeFiles           DIABDAT.MPQ  extern    launcher  resources
celview.ini  cmake_install.cmake  Diablo.exe   freeablo  Makefile

I have to admit this isn't a user-friendly application.

Do you plan to create a GUI for this program?

**Comment by wheybags** [comment]
No, it's not really meant for users, just a convenient little program for
developers if they need to extract a file or two and aren't on windows (on
windows you can use ladik's mpq editor)

**Comment by gbudny** [comment]
Thanks for the answer.

**Comment by Ragora** [comment]
Sounds like it should at least enforce the two-argument requirement and dump a small help in the event argc != 3.
