### ISSUE TITLE
[Warning] - Failed to load texture from

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#199]
Hi

I noticed that one of the textures do not load properly in Freeablo.

Did you notice the similar issue with Freeablo?

ui_art\logo.pcx
ui_art\title.pcx
levels\towndata\town.pal
data\diabsmal.cel
levels\towndata\town.pal
data\PentSpin.cel
[Warning] - Failed to load texture from .
levels\towndata\town.pal
data\inv\objcurs.cel
levels\towndata\town.pal
data\char.cel

**Comment by konopka90** [comment]
Ready to close https://github.com/wheybags/freeablo/pull/202
