### ISSUE TITLE
(SBaseDumpData.cpp.o) has no symbols (Mac)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#208]
Hi

I noticed this information when I was compiling Freeablo on Mac OS X:

212 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libStormLib.a(SBaseDumpData.cpp.o) has no symbols
213 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libStormLib.a(SBaseDumpData.cpp.o) has no symbols

https://gist.github.com/gbudny/4038b872c45679845f7a

**Comment by wheybags** [comment]
dunno what this is, I get it on linux too, but it's not our problem, and stormlib does work
