### ISSUE TITLE
hidden by macro definition [-Wkeyword-macro] - the warning (Mac)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#214]
Hi

I want to inform you that I noticed this warning on Mac OS X

"Building CXX object test/CMakeFiles/test_cel.dir/cel.cpp.o
/Users/gbudny/Desktop/Diablo/freeablo/test/cel.cpp:11:9: warning: keyword is
      hidden by macro definition [-Wkeyword-macro]
#define private public
        ^
1 warning generated.
[100%] Linking CXX executable ../test_cel
[100%] Built target test_cel"

https://gist.github.com/anonymous/c5e6b75597c1a3e830fb

Darwin user-Mac-mini.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

**Comment by wheybags** [comment]
That's fine, the whole point is to hide that keyword :p (it's a test file)
