### ISSUE TITLE
CMake doesn't detect qt (Mac)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#221]
Hi

Mac users should install Qt from Homebrew if they want to compile Freeablo on Mac OS X, but CMake can't find qt: 

qt5:

https://gist.github.com/gbudny/7a462eb069a462954e78

brew install qt5

In this case, I used this command:

export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.5.1_2/

https://gist.github.com/gbudny/fae8f369fe6e0ca74d13

Do you plan to modify the script cmake in order to automatically detects the library qt from brew on the Mac?

**Comment by kimsama** [comment]
same on here, resolved with the following:
```
export CMAKE_PREFIX_PATH="where_qt5_installed_directory"
```

**Comment by gbudny** [comment]
The current version of qt is 5.6.0.

**Comment by wheybags** [comment]
we no longer use qt
