### ISSUE TITLE
The issue with libpng when I use dialogs (Mac)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#224]
Hi

I noticed this warning when I tried to talk with one of the NPCs:

NPCdrunk
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
tick time exceeded by 17ms
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

Edit: I have the same issues with other NPCs:

NPCsmith
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
tick time exceeded by 202ms
NPCsmith
tick time exceeded by 2ms
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

NPCtavern
libpng warning: iCCP: known incorrect sRGB profile
tick time exceeded by 151ms
NPCtavern
libpng warning: iCCP: known incorrect sRGB profile

**Comment by Hydroque** [comment]
The issue is justified. Incorrect sRGB profiles are indeed a bug in the file format and should be patched. However, I don't think it matters now.
