### ISSUE TITLE
No formula found for 'libtomcrypt' (MAC)

### ISSUE THREAD

**Issue by kimsama** [wheybags/freeablo#225]
```
brew install libtomcrypt 
```

got result no found formula such as 'libtomcrypt' 

tried the following:

```
brew search crypt
```

but there are no 'libtomcrypt' can be found. 

Any ideas?

**Comment by gbudny** [comment]
I think that libtomcrypt was removed from the Homebrew repository, but you can try to install it from Boneyard:

https://github.com/Homebrew/homebrew-boneyard

**Comment by kimsama** [comment]
```
$brew tap homebrew/boneyard
$brew install libtomcrypt
```

got the following errors:

```
Last 15 lines from /Users/kims/Library/Logs/Homebrew/libtomcrypt/01.make:
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:277:24: error: constraint 'I' expects an integer constant expression
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:368:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
./src/headers/tomcrypt_macros.h:376:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
4 errors generated.
make: *** [src/ciphers/aes/aes.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/ciphers/aes/aes_enc.o] Error 1

READ THIS: https://git.io/brew-troubleshooting
libtomcrypt was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

**Comment by gbudny** [comment]
Did you try to use this command?

brew install https://raw.githubusercontent.com/Homebrew/homebrew-boneyard/master/libtomcrypt.rb

**Comment by kimsama** [comment]
Yes, but no luck.

**Comment by gbudny** [comment]
I think that I found a temporary solution to this issue that will help you to run this game.
I installed libtomcrypt from Macports, and Freeablo didn't detected it:

[ 90%] Linking CXX executable ../../freeablo
clang: error: no such file or directory: '/usr/local/lib/libtomcrypt.a'
make[2]: *** [freeablo] Error 1
make[1]: *** [apps/freeablo/CMakeFiles/freeablo.dir/all] Error 2
make: *** [all] Error 2

I copied this file libtomcrypt.a to /usr/local/lib, and later I tried to compile it again.

The game works, but I don't have a better solution.

**Comment by kimsama** [comment]
Which means 'macport' still support 'libtomcrypt'. 

Though I removed 'macport' long time ago, I'll try with that way later. 

Thank you for pointing it out. 

-Kim

**Comment by gbudny** [comment]
This toolkit doesn't have a maintainer, but they didn't remove it from MacPorts:

https://www.macports.org/ports.php?by=name&substr=libtomcrypt

**Comment by lewisou** [comment]
git clone https://github.com/libtom/libtomcrypt.git
cd libtomcrypt
git checkout tags/1.17
make
Then I got libtomcrypt.a

**Comment by wheybags** [comment]
we now use hunter for dependencies
