### ISSUE TITLE
OSX installation problems(MAC)

### ISSUE THREAD

**Issue by kimsama** [wheybags/freeablo#226]
On OSX 10.11.4, there are several problems on the installation of freeablo:

1) Cannot install 'boost' and 'boost-python'. #https://github.com/BVLC/caffe/issues/3936
2) No 'libtomcrypt' can be installed even with 'boneyard'

Anyone solved those problems with OSX 10.11.x?

**Comment by gbudny** [comment]
Do you have a similar issue with boost' and boost-python?

"My machine stuck and the screen is showing "...updated 13743 targets..." for around 12 hours."

I don't have this version of Mac OS X, but I had to wait 2 hours in order to finish the installation of boost on Mac OS X 10.10.5.

**Comment by kimsama** [comment]
yep, it took over several hours to finis for me.

**Comment by wheybags** [comment]
obsoleted by hunter
