### ISSUE TITLE
Boost error guimanager.cpp

### ISSUE THREAD

**Issue by antoniocaruso** [wheybags/freeablo#229]
I followed your setup for the installation:
I have: boost 1.60.0_2 (installed with --python) and
            boost-python 1.60.0 
when I build with cmake I have:

```
[ 73%] Built target StormLib
[ 74%] Built target Settings
[ 75%] Built target Input
[ 78%] Built target Cel
[ 79%] Built target FAIO
[ 81%] Built target Levels
[ 83%] Built target Render
[ 83%] Built target Audio
[ 85%] Built target Misc
[ 86%] Built target DiabloExe
Scanning dependencies of target freeablo
[ 86%] Building CXX object apps/freeablo/CMakeFiles/freeablo.dir/fagui/guimanager.cpp.o
In file included from /usr/local/include/boost/property_tree/string_path.hpp:17:0,
                 from /usr/local/include/boost/property_tree/ptree.hpp:16,
                 from /usr/local/git/freeablo-v0.3-source/components/input/hotkey.h:4,
                 from /usr/local/git/freeablo-v0.3-source/components/input/common.h:5,
                 from /usr/local/git/freeablo-v0.3-source/apps/freeablo/fagui/guimanager.cpp:18:
/usr/local/include/boost/property_tree/detail/ptree_utils.hpp:31:45: error: macro "toupper" passed 2 arguments, but takes just 1
             return std::toupper(c1, m_locale) < std::toupper(c2, m_locale);
                                             ^
/usr/local/include/boost/property_tree/detail/ptree_utils.hpp:31:74: error: macro "toupper" passed 2 arguments, but takes just 1
             return std::toupper(c1, m_locale) < std::toupper(c2, m_locale);
                                                                            ^
and several
In file included from /usr/local/include/boost/type_traits/ice.hpp:17:0,
                 from /usr/local/include/boost/python/detail/def_helper.hpp:9,
                 from /usr/local/include/boost/python/class.hpp:29,
                 from /usr/local/include/boost/python.hpp:18,
                 from /usr/local/git/freeablo-v0.3-source/apps/freeablo/fagui/guimanager.cpp:16:
/usr/local/include/boost/type_traits/detail/ice_not.hpp:17:72: note: #pragma message: NOTE: Use of this header (ice_not.hpp) is deprecated
 # pragma message("NOTE: Use of this header (ice_not.hpp) is deprecated")


```

I know that it seams more a problem of the interaction between boost / boost-python and that
source. But I do not know how to solve.

**Comment by konopka90** [comment]
During analysis of your logs I noticed error in file

> /usr/local/git/freeablo-v0.3-source/apps/freeablo/fagui/guimanager.cpp:18:
but 18th line in file guimanager.cpp on master is "{" so how it is possible ? Did you clone latest version of freeablo ?
What OS do you use?

**Comment by antoniocaruso** [comment]
I work on OSX El Capitain.

OK, I just did a clean install with a git clone. Now it works, or at least, it works until the build of celview..
at least I can test the freablo executable . There are still problems with celviewer:

 Scanning dependencies of target celview there are problems with Qt and celview, 

`Scanning dependencies of target celview
[ 91%] Building CXX object apps/celview/CMakeFiles/celview.dir/main.cpp.o
In file included from /usr/local/git/freeablo/apps/celview/main.cpp:1:
In file included from /usr/local/git/freeablo/apps/celview/mainwindow.h:4:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QMainWindow:1:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qmainwindow.h:37:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qwidget.h:45:
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:45:1: error: unknown type name 'Q_DECL_CONST_FUNCTION'
Q_DECL_CONST_FUNCTION inline uint qHash(QSizePolicy key, uint seed = 0) Q_DECL_NOTHROW;
^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:45:23: error: expected unqualified-id
Q_DECL_CONST_FUNCTION inline uint qHash(QSizePolicy key, uint seed = 0) Q_DECL_NOTHROW;
                      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:49:5: error: expected expression
    Q_GADGET
    ^
/usr/local/include/QtCore/qobjectdefs.h:173:18: note: expanded from macro 'Q_GADGET'
#define Q_GADGET \
                 ^
In file included from /usr/local/git/freeablo/apps/celview/main.cpp:1:
In file included from /usr/local/git/freeablo/apps/celview/mainwindow.h:4:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QMainWindow:1:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qmainwindow.h:37:
In file included from /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qwidget.h:45:
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:24: error: variable has incomplete type 'class Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
                       ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of 'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:32: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_type f2) \
                               ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:60: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_type f2) \
                                                           ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2471:81: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, Flags::enum_type f2) \
                                                                                ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2472:17: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
{ return QFlags<Flags::enum_type>(f1) | f2; } \
                ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:32: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags::enum_type> f2) \
                               ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:60: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags::enum_type> f2) \
                                                           ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2473:88: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
Q_DECL_CONSTEXPR inline QFlags<Flags::enum_type> operator|(Flags::enum_type f1, QFlags<Flags::enum_type> f2) \
                                                                                       ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:161:31: error: incomplete type 'QSizePolicy' named in nested name specifier
Q_DECLARE_OPERATORS_FOR_FLAGS(QSizePolicy::ControlTypes)
                              ^~~~~~~~~~~~~
/usr/local/include/QtCore/qglobal.h:2474:50: note: expanded from macro 'Q_DECLARE_OPERATORS_FOR_FLAGS'
{ return f2 | f1; } Q_DECLARE_INCOMPATIBLE_FLAGS(Flags)
                                                 ^~~~~
/usr/local/include/QtCore/qglobal.h:2467:36: note: expanded from macro 'Q_DECLARE_INCOMPATIBLE_FLAGS'
inline QIncompatibleFlag operator|(Flags::enum_type f1, int f2) \
                                   ^~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:164:18: error: variable has incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDataStream &operator<<(QDataStream &, const QSizePolicy &);
                 ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of 'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:164:29: error: expected ';' after top level declarator
Q_WIDGETS_EXPORT QDataStream &operator<<(QDataStream &, const QSizePolicy &);
                            ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:165:18: error: variable has incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
                 ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of 'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:165:29: error: expected ';' after top level declarator
Q_WIDGETS_EXPORT QDataStream &operator>>(QDataStream &, QSizePolicy &);
                            ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:169:18: error: variable has incomplete type 'Q_WIDGETS_EXPORT'
Q_WIDGETS_EXPORT QDebug operator<<(QDebug dbg, const QSizePolicy &);
                 ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:47:7: note: forward declaration of 'Q_WIDGETS_EXPORT'
class Q_WIDGETS_EXPORT QSizePolicy
      ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:169:24: error: expected ';' after top level declarator
Q_WIDGETS_EXPORT QDebug operator<<(QDebug dbg, const QSizePolicy &);
                       ^
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:172:13: error: incomplete type 'QSizePolicy' named in nested name specifier
inline void QSizePolicy::transpose() {
            ^~~~~~~~~~~~~
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qsizepolicy.h:43:7: note: forward declaration of 'QSizePolicy'
class QSizePolicy;
      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
`

**Comment by gbudny** [comment]
I used this script to compile Freeablo on Mac

#!/bin/bash
cd Desktop/
mkdir Diablo1
cd Diablo1
git clone -b https://github.com/wheybags/freeablo.git
cd freeablo 
git submodule update --init
cd ..
mkdir build
cd build
ln -s ../freeablo/resources
export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.0/
cmake ../freeablo
make

I recommend checking if there is a new version of qt in Homebrew.

You should use a launcher to point out a localization of files like DIABDAT.MPQ and Diablo.exe. 

I think that I saw an error 22 when I successfully compiled Freeablo, and I tried to compile it again in the same directory.

**Comment by gbudny** [comment]
Mac users should remove all the versions of QT, and they should install qt5 again.

**Comment by wheybags** [comment]
This code is all replaced now
