### ISSUE TITLE
Bug - showTitleScreen

### ISSUE THREAD

**Issue by konopka90** [wheybags/freeablo#233]
When `showTitleScreen` is set to false in file `settings-default.ini` freeablo crashes.

**Comment by pengyz** [comment]
Is it has been fixed? 
I test it on windows by set **showTitleScreen**  to false  but freeablo runs well,no any crashes.Or it only crash at a specific platform? I only test on windows.

**Comment by wheybags** [comment]
new gui is completely different, so this issue is almost certainly gone
