### ISSUE TITLE
 'const' qualifier on reference type 'FrameBytesRef' - 11 warnings generated (Mac)

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#236]
I noticed many warnings on Mac when I was compiling Freeablo:

https://gist.github.com/gbudny/8581c716af96d720ecccb55727e8824f

**Comment by konopka90** [comment]
Sure, there is no const reference in syntax, reference is const from definition..

**Comment by gbudny** [comment]
Thanks.

It works.

**Comment by konopka90** [comment]
Maybe it's good idea to add clang compiler to travis
