### ISSUE TITLE
RAII IO

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#247]
The current io system is implemented in components/faio, as a series of functions similar to the fopen/tread c io functions.
It would be nice to have a clean RAII class that would use these functions to open the file in its constructor, and close it in it's destructor.
I'd still want it's member functions to be similar to dread etc, as opposed to going the route of c++ streams though

This could be a good task for someone new to the codebase ehi wants to get their feet wet.

**Comment by SGBon** [comment]
I might give it a look. Do you want to keep the same interface with the friend functions? And if so should they be adapted as wrappers that call internal member functions or still contain all the code?

**Comment by wheybags** [comment]
I wouldn't remove the existing functions - I'd just implement the wrapper on top of them, so the wrapper would still have an FAFile* member variable.

**Comment by SGBon** [comment]
Alright then

**Comment by pengyz** [comment]
I will do something about it too.
