### ISSUE TITLE
DIABDAT.MPQ  & Diablo.exe

### ISSUE THREAD

**Issue by lewisou** [wheybags/freeablo#260]
Where to get these two files? 

After I had eventually compiled the source code on my Mac, I realized I still needed DIABDAT.MPQ and Diablo.exe to play the game.

**Comment by Asfhy** [comment]
Buying your own legal copy of the game. If you have the game, you just need to install the game under Darwine or a virtual machine, update to the version 1.09 (Without expansion) and copy thoose two files. That files are under the copyright af Blizzard, so you need to have your copy of the game with it's license to use them.

**Comment by wheybags** [comment]
Yup
