### ISSUE TITLE
Re-ad inventory menu

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#271]
Before we switched gui library from librocket to nuklear we had an inventory menu, with full support for icons and moving stuff around.

https://github.com/wheybags/freeablo/commit/abe20a463196964291f7121739c419f5a9afe518 is the last commit before merging the gui replacement, you can see this branch for an example.

**Comment by rsantellan** [comment]
@wheybags on the readme say to install librocket to compile freeablo, that is deprecated?
How is the best way to create the developing setup? I'm on Ubuntu 14.04

**Comment by wheybags** [comment]
closed by @Predelnik
