### ISSUE TITLE
freeablo mac build

### ISSUE THREAD

**Issue by gbudny** [wheybags/freeablo#277]
Hi

I can't compile a new version of Freeablo on Mac OS X:

https://gist.github.com/anonymous/2be57c83aef4d800dcb3b797f7f74233

**Comment by wheybags** [comment]
I don't have access to a mac atm, and i wouldn't be surprised if a lot of stuff is broken.
I'm setting up a mac vm as we speak, but im not sure if I will fix everything soon, or leave it for another time.
OSX support isn't my biggest priority unfortunately, but I'd like to make it happen :(

**Comment by wheybags** [comment]
Also, all binaries are going to be statically linked in the near future (#278), so these problems should largely go away

**Comment by gbudny** [comment]
Thanks for the answer.

I will be happy to test new versions of Freeablo on Mac if you fix these issues. 

Some issues are not serious, but it makes the compilation process harder on the Mac e.g. the detection of Qt by cmake.

**Comment by wheybags** [comment]
hey, we're using hunter now, so can you try again? The renderer might well not work on mac atm

**Comment by gbudny** [comment]
Thank you.

I can compile it now.

**Comment by wheybags** [comment]
It should stay working too, or at least compiling, since there is travis
for osx now.
