### ISSUE TITLE
CI for clang + msvc warnings

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#280]
Set up CI for clang warnings in much the same way we have it for g++ (see .travis.yml), and also do the same for msvc (appveryor.yml)
Also, of course, fix the warnings generated

**Comment by Predelnik** [comment]
Just curious, what is the point in enabling warnings-as-errors only in CI? It just moves fixing these warnings to later stage imo.

**Comment by wheybags** [comment]
It's a pain in the ass to deal with compile errors for unused variables
from commenting out a block of code while testing something. Also, you
never know which compiler version someone is gonna use, so having the
master branch fail to build for them because they have a newer gcc version
is also a pain in the ass

**Comment by Predelnik** [comment]
Maybe then make it cmake option so it could be turned on in cmake-gui quickly for developers locally if they wish so (and disabled by default) and then just turn on this option in CI scripts.

**Comment by wheybags** [comment]
Yeah, that makes sense
