### ISSUE TITLE
Lines between textures.

### ISSUE THREAD

**Issue by Predelnik** [wheybags/freeablo#297]
![image](https://user-images.githubusercontent.com/2133957/30818941-58338924-a21d-11e7-8327-84c08cc4a51f.png)
When I run freeablo on my laptop, there is this issue with rendering textures. (note green lines between tiles). I don't have much experience with opengl to figure out what may cause this, especially since it's obviously inconsistent on different GPUs/systems. I wonder if anyone has any clue what could cause this?

My laptop is ROG GL552VX running win10.

**Comment by wheybags** [comment]
Huh, weird, what is your GPU?

**Comment by Predelnik** [comment]
Ok so it turns out laptop has two GPUs, 
1) Intel HD Graphics 530.
2) NVIDIA GeForce GTX 950m
I turned on option which forces it to use NVIDIA and the problem is gone, so it looks like this happens only when rendering with Intel HD Graphics. So I think the priority of this issue is not high but it's still a bit weird.

**Comment by wheybags** [comment]
Yeah, that's a system called Nvidia optimus, and unfortunately it's quite
common :s, so it might well be a problem.
That said, the issue is probably just with the Intel drivers, not Optimus
itself, but should still try to solve it at some point

**Comment by LBdN** [comment]
The strange display is possibly due to glEnabled(GL_POLYGON_SMOOTH). it works differently depending on the GPU.
more detail there : https://stackoverflow.com/questions/30522880/how-to-avoid-black-lines-between-triangles-on-modern-gpus

**Comment by Necrolis** [comment]
Most drivers tend to have issues from setup to setup, however there is a pattern to the issue here, its non-existent in the upper-left corner and then become more pronounced; this may indicated fp accuracy issues.

With regards to NV Optimus and the AMD equivalent, you can always enable the discrete card using the following (if the driver isn't set to override these): 

`extern "C"
{
	__declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 0x00000001;
	__declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
}`

**Comment by Predelnik** [comment]
Ok so after some experimenting it turns out that changing "#version 320 es" in shaders to any version starting from 130 (without es) makes everything fine for Intel HD. I have no idea what es actually means but it looks like Intel HD has some problem with it.
