### ISSUE TITLE
SHA1 of DIABDAT.MPQ and DIABLO.EXE

### ISSUE THREAD

**Issue by Hydroque** [wheybags/freeablo#323]
What is the SHA1 of these two files `DIABDAT.MPQ and DIABLO.EXE` that freeablo supports?

**Comment by mewmew** [comment]
For `DIABLO.EXE` refer to https://github.com/wheybags/freeablo/blob/55ec3b6369b05351762928943e214110fb22305b/resources/exeversions/versions.ini.

Currently, two versions are supported. Version 1.09 and 1.09b, which have MD5 sums `0d1a2b10f8b7fc1a388109bd8abf05d1` and `da62d5cd8bd71a0b66e6d4ef7a111233`, respectively.

For the `DIABDAT.MPQ`, I don't know if this is checked somewhere. @wheybags care to provide some insight?

**Comment by wheybags** [comment]
It's not checked, and as far as I know they're all the same. I've only ever
used the version from v1.09 anyway

**Comment by Hydroque** [comment]
Thanks
