### ISSUE TITLE
proper direction type

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#327]
We just use an into for direction, where the values 0-7 encode the compass directions.
This is what enums are for :p

**Comment by Predelnik** [comment]
Also it'd be nice to synchronize with Diablo's enum used for direction (https://github.com/sanctuary/notes/blob/c6779ad795fc78efe515dd48f55901ef7642fb95/enums.h#L67)
I encountered it during item drop, if you click on player's tile it defaults to 0 in Diablo direction, but in Freeablo it's 7. (https://github.com/wheybags/freeablo/blob/2e817003b13adba8911489a04c2f215074f57e28/apps/freeablo/faworld/player.cpp#L258) That's not a big thing of course but maybe there will be similar problems with default direction along the way.
