### ISSUE TITLE
Pause menu is buggy when you have inventory open

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#338]
- cannot click menu entries
- If I have an item in my cursor, it stays as my cursor

**Comment by wheybags** [comment]
@Predelnik assigned to you since you wrote this code

**Comment by Predelnik** [comment]
The second point is actually true to original game, if you pick something in hand you have to navigate pause menu with it :)

**Comment by wheybags** [comment]
:D that's kinda great
