### ISSUE TITLE
Handle placement of loot in inventory

### ISSUE THREAD

**Issue by mewmew** [wheybags/freeablo#353]
To get the correct feeling, Freeablo should place looted items in an same empty slot of the inventory according to the same logic as the original Diablo 1 implementation.

As based on `0x43E2D1` of the PC debug release, the placement of an item of *width*x*height* can be described as,

```go
// try 1x1 on inv slot 30-39
// try 1x1 on inv slot 20-29
// try 1x1 on inv slot 10-19
// try 1x1 on inv slot 0-9
//
// try 1x2 on inv slot 29-20
// try 1x2 on inv slot 9-0
// try 1x2 on inv slot 19-10
//
// try 1x3 on inv slot 0-19
//
// try 2x2 on inv slot:
//    8, 28,
//    6, 26,
//    4, 24,
//    2, 22,
//    0, 20
// try 2x2 on inv slot:
//    21, 23, 25, 27
// try 2x2 on inv slot:
//    1, 3, 5, 7
// try 2x2 on inv slot: 10-18
//
// try 2x3 on inv slot: 0-8
// try 2x3 on inv slot: 10-18
```

![Inventory slots](https://raw.githubusercontent.com/sanctuary/graphics/master/inventory.png)

The exact locations of inv slot 0-39 are described by the layer names of the GIMP XCF file: https://github.com/sanctuary/graphics/blob/master/inventory.xcf

**Comment by Predelnik** [comment]
Ok that looks more crazy than I thought, but I've done current logic before reversing anything based on pure experiment so it's pretty obvious that it's only approximate.

**Comment by mewmew** [comment]
Actually, the behaviour of the logic is "what you want", even if complex.

# Potions and other 1x1 items

* try 1x1 on inv slot 30-39
   - *Place 1x1 items on the bottom row, left to right.*
* try 1x1 on inv slot 20-29
* try 1x1 on inv slot 10-19
* try 1x1 on inv slot 0-9
   - *Place 1x1 items on the top row, left to right.*

# Daggers and other 1x2 items

* try 1x2 on inv slot 29-20
   - *Place 1x2 items on the bottom row, left to right.*
* try 1x2 on inv slot 9-0
   - *Place 1x2 items on the middle row, left to right.*
* try 1x2 on inv slot 19-10
   - *Place 1x2 items on the top row, left to right.*

etc.

**Comment by Predelnik** [comment]
Yeah I understand that it needs to be reproduced but the fact that it's done differently for different items already was questionable for me (I obviously never noticed that while playing the game). Then I found out that it could be different for the same item (for shield which returns to hand when you equip two-handed weapon). But now I see that for 2x2 item the order is something really insane that makes me wonder why all the effort was made to make it that complex, I doubt that it really matters somehow for most of the players :)
Sorry for my rant.

**Comment by mewmew** [comment]
Rant granted.

Actually 2x2 makes the most sense ^^ You want helmets to stack on top of one another.

```
##########aa
##########aa
##########bb
##########bb
```

And these 2x2 items go from right to left (as to take up empty space, and thus stack on top of one another).

I think the original developers of Diablo basically encoded the algorithm for efficient Tetris packing into the inventory item placement code :)

**Comment by wheybags** [comment]
Personally I'm not too bothered with this but if someone else feels like adding "tetris packing" then by all means go ahead :p
