### ISSUE TITLE
Freeablo on Ubuntu crash on start

### ISSUE THREAD

**Issue by dafioram** [wheybags/freeablo#365]
After successful building freeablo on Ubuntu 17.10 it crashes if I try to run it.

Messages:
skipping stormlib init - won't be able to read files in MPQ archives
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
Diablo.exe v109 detected
File "levels/towndata/town.pal" not found
FAFileWrapper::FAfread: faFile is NULL.
File "ctrlpan/smaltext.cel" not found
ASSERTION FAILED: (file.isValid()) in /home/ubuntu/Documents/freeablo/components/cel/celdecoder.cpp:162

Any ideas?

**Comment by wheybags** [comment]
Did you run the launcher and set the now and exe locations? Should really
just have it do that automatically or something because a few people have
come here asking about that.

**Comment by dafioram** [comment]
Using the launcher solved it.
