### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by ijemafe** [wheybags/freeablo#367]
The latest release is v0.3 from August 5, 2015, and it does not seem to support Windows 10. This message is displayed before crashing on startup:

```
Qt: Untested Windows version 10.0 detected!
```

Please tag and release the past 2.5 years of fixes. Thanks!

**Comment by wheybags** [comment]
I'm planning on releasing 0.4 once I have the new multiplayer working.
You should be able to go down into the dungeon in multiplayer and kill
monsters, making it a decent approximation of the core gameplay.
Subsequent releases will focus on visuals and accuracy of simulation.
The current state of multiplayer is fairly advanced, I'm working on making
sure level generation is fully deterministic, and then will need to sync
inventories/shops properly, but after that is done it should be a solid
base to continue on.
I'm hoping to finish within a month or so, but I'm working on it in my free
time, so I can't say exactly.

**Comment by ROCKNROLLKID** [comment]
Hello. I just recently came across this not that long ago. I also noticed tons of source code work, but no official release since 2015. However, my concern is that this also doesn't work on Windows 10 and I don't seem to see any work done on improving/adding Windows 10 compatibility over the past 2 years.

My question is: Will you be adding/improving Windows 10 support before release 0.4 update?

**Comment by wheybags** [comment]
Oh, I didn't know it wasn't working on windows 10, I only have 8.
I'll make sure to fix that before release, yes.

**Comment by wheybags** [comment]
Hey, so I get that this a bit of a late response, but at the time, I wasn't honestly sure myself how to respond.
I basically consider the engine mostly ready for a 0.4 release. What I want to do before then is smooth out a few rough edges, and fix some bugs.
So, my todo list is:
- Fix any currently known bugs, then go looking for any more I can find.
- Finalise the multiplayer implementation - this is something I'm in the middle of now. What it means is I'd like to have a mp foundation that not only works, but will work over an actual lossy internet connection, not just my home LAN.
- Add in a gui for connecting to an MP game.

Essentially, the goal is a (mostly) bug free version of what we have now, but with much better mp support.
I hope that answers your question.

**Comment by predator8bit** [comment]
This reads more like a 1.0 release to me than an 0.4. I think you should have more releases with a few things missing here and there, rather than stressing on completing everything for the few that you do.

I see many projects doing time based schedules and they works out for them.

**Comment by wheybags** [comment]
This todo list is now mostly done. In the next while, I'm going to record a short demo video, and do a release.

**Comment by predator8bit** [comment]
So how are things advancing?

**Comment by mewmew** [comment]
This issue can be closed as of rev 87c4ce5cc34cfa88960266a7d94bfea9af1cecfb.

**Comment by wheybags** [comment]
yup :tada:
