### ISSUE TITLE
Make use of information from devilution as long as you can.

### ISSUE THREAD

**Issue by ChrisPHL** [wheybags/freeablo#372]
Hey folks,

I like your project so much as I'm one of that people who remember the game from the beginning. Just watching others playing Diablo for hours while having a good time in a so called "Cyberspace Cafe" makes me kind of sentimental...

So here's my hint for you: There's just another project that did document a whole bunch of disassembled code from the original game: https://github.com/galaxyhaxz/devilution.
I suggest clone the code as fast as you can because there's a good chance that Blizzard will engage the owner of the repository and force him shutting down the archive...

Good luck and keep up the good work!

**Comment by RED-404** [comment]
The documentation maybe* but the code would be quite dangerous.
Stick with the Wine and ReactOS approch.

Devilution is useful for fixing and modding Diablo but leagaly it's nearly useless or even detramental for something like Freeablo.

**Comment by wheybags** [comment]
Yup, cool project but not gonna be used here.
