### ISSUE TITLE
[Question]  How to contribute if new/don't own original Diablo?

### ISSUE THREAD

**Issue by iloveket** [wheybags/freeablo#385]
Just writing to ask if there's any way to contribute to debugging and/or testing if the person doesn't have the original assets from Diablo, and if they're fairly new to open-source in general.

**Comment by wheybags** [comment]
Nope, sorry, not possible at the moment, and unlikely to happen for a long time (or ever?)

**Comment by tilkinsc** [comment]
The problem is the assets are copyrighted. Distribution is unethical and probably illegal aka another business venture for blizzard.We could, however, clone the file format and put blanks for filler to be added. Although its filler, testing should still work. This way no assets are truly copied.

**Comment by sskras** [comment]
O think there is way to do that.  One can fork this project into a demo version (and call it freeablo-spawn) so it can work with the assets provided in the original demo by Blizzard.  That would still gain lots of useful patches I think.

**Comment by tilkinsc** [comment]
Is distribution of the demo okay by them? Plus, I doubt the demo has everything.

**Comment by greysondn** [comment]
Blizzard borderline encouraged open distribution of the dmo back in the day, with a copy of it - able to run without the CD - shipping on the original commerical Diablo discs. I would assume they're okay with it being distributed, although to them the premise would likely be "if we give them a demo and they like it, they'll buy the full game" - not a reimplementation of the game's engine.

**Comment by sskras** [comment]
@tilkinsc:
> Is distribution of the demo okay by them? 

What do you mean by distribution?  My scenario was this: 
* you download a demo, 
* install it,
* build the freeablo-spawn,
* copy it into the demo folder,
* run / debug it.

No need to distributed anything.

> Plus, I doubt the demo has anything.

Well, by writing this:

> so it can work with the assets provided in the original demo by Blizzard. That would still gain lots of useful patches

I meant exactly the same as @greysondn writes:
> A gamefaqs thread says that the spawn version (AKA demo) is Warrior only, down to floor 3... BUT you could play on Battle.net. I would assume so long as those limitations are maintained Blizzard would have no significant issues with it.

One just try to reimplement shortened version of Diablo 1.  As soon as it get near to finish, one would have a lot of code to contribute to the main project.  

O maybe fork isn't needed at all – maybe spawn/shareware/demo mode can be incorporated into the main project (which could detect what kind of original installation is found: Full or Spawn/Shareware/Demo, and act accordingly.
