### ISSUE TITLE
Does not work on Windows 10

### ISSUE THREAD

**Issue by mfgabriel92** [wheybags/freeablo#387]
I downloaded an ISO copy of Diablo I, I've patched it and tried to follow the instructions. My installation folder did not have a DIABDAT.MPQ file in it so I tried copying the one from the mounted drive. After copying the files, I had errors messages saying the code execution cannot proceed because a few DLLs were not found. They are MSVCR120.dll and MSVCP120.dll. What am I missing? Why didn't I have DIABDAT.MPQ in my installation folder?

**Comment by Dramacydal** [comment]
First finds in Google say you must install some redistributable package

**Comment by wheybags** [comment]
There are currently problems on windows 10 https://github.com/wheybags/freeablo/issues/369
