### ISSUE TITLE
run

### ISSUE THREAD

**Issue by bgbruno** [wheybags/freeablo#406]
Hello - I'm huge fun od this game and when I saw opensource activity I have to downloaded it 😊

I successfully compile code on #macos by steps in $[readme.md](https://github.com/wheybags/freeablo/blob/master/readme.md)

then I run app, show black screen, mouse cursor, I see change resolution to highest by the mouse cursor and then console error

    skipping stormlib init - won't be able to read files in MPQ archives
    File "Diablo.exe" not found

that makes no sense because I run it in $macos

Q any idea why?
Q it's possible activate some debug log?

**Comment by tilkinsc** [comment]
Stormlib needs installed, which should of been handled by hunter or you lack it in the repository. Wherever it lays.

**Comment by wheybags** [comment]
You need to run the launcher first and set up paths to your original game files.
`./launcher`
