### ISSUE TITLE
Validate MPQ files

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#427]
We should valiudate the MPQ files a user picks when they run the launcher. See https://github.com/wheybags/freeablo/commit/e9463c409b62056a1ec14bdd490233e3f3a5d3f0#r32185394 for more details/hashes

**Comment by AJenbo** [comment]
With the recent GoG release the state is still unchanged:

Original US md5: 68f049866b44688a7af65ba766bef75a
EU/Mac/GoG md5: 011bc6518e6166206231080a4440b373
(the only difference being the logo.smk being partially broken in the first one)

Updates do not affect the diabdat.mpq file, instead files are overwritten via the Patch_rt.mpq file. To this day only UI elements relating to multiplayer have been updated this way.
