### ISSUE TITLE
gear display

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#47]
displaying the correct player image for the gear you have equipped

**Comment by mloccy** [comment]
I think this means displaying items in the inventory widget. If that's what it means then #159 closes this

**Comment by mloccy** [comment]
This is ready to go.

**Comment by konopka90** [comment]
I'm not sure that but what @wheybags think ?

**Comment by Hydroque** [comment]
With #170 this is proven to be needing to be closed.

**Comment by wheybags** [comment]
Actually that went away a while ago but @predelnik re-added this functionality recently
