### ISSUE TITLE
Figure out how arches work in the l1 tileset

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#52]
see rnd2,3,5, for examples. Tileset does not seem to contain middles for the arches

**Comment by d33tah** [comment]
> Attaching some email correspondence related to this issue, so the details are in the open.

Was this correspondence with the Diablo devs?

**Comment by mewmew** [comment]
> Was this correspondence with the Diablo devs?

No, it was just an email conversation between wheybags and me during March last year, when he was still working on his dissertation. I decided to upload a copy of the correspondence to the relevant issue, as others may be interested in the details : )

**Comment by wheybags** [comment]
This is in the game now
