### ISSUE TITLE
ui chroma key transparency

### ISSUE THREAD

**Issue by wheybags** [wheybags/freeablo#96]
eg the diablo logo in the pause screen

**Comment by zykis** [comment]
<code>import Image</code>
<code>img = Image.open('/ui_art/smlogo.pcx')</code>
<code>img = img.convert("RGBA")</code>
<code>datas = img.getdata()</code>
<code>newData = []</code>
<code>for item in datas:</code>
<code>    if (item[0] == 0 and item[1] == 255 and item[2] == 0):</code>
<code>        newData.append((0, 0, 0, 0))</code>
<code>    else:</code>
<code>        newData.append(item)</code>
<code>img.putdata(newData)</code>
<code>img.save("/ui_art/smlogo.png", "PNG")</code>

This script converts an image, but i have no idea how make it works for element within *.rml file.

**Comment by wheybags** [comment]
Probably do it with a custom decorator, or some magic bit in the image url, like &alpha=0,255,0 or something
